/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Danmu: typeof import('./src/components/Danmu/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Medal: typeof import('./src/components/Medal/index.vue')['default']
  }
}
